### ISSUE TITLE
SPARQL MINUS clause not supported by Comunica?

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/network-of-terms-api#116]

**Comment by EnnoMeijers** [comment]
Trying to add this the following query to the catalog but it the api throws an error, it looks like the SPARQL MINUS clause is not supported? 
[wikidata-entities-places query.txt](https://github.com/netwerk-digitaal-erfgoed/network-of-terms-api/files/5939462/wikidata-entities-places.query.txt)

**Comment by sdevalk** [comment]
Comunica should support MINUS operations [1], but perhaps we haven't configured this properly in the Network of Terms. I'll look into this!

[1] https://github.com/comunica/comunica/tree/master/packages/actor-query-operation-minus

**Comment by sdevalk** [comment]
Update: this looks like a Comunica bug - https://github.com/comunica/comunica/issues/779

**Comment by sdevalk** [comment]
Solved in https://github.com/comunica/comunica/issues/779
