### ISSUE TITLE
Link to website page gives 404

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/network-of-terms-api#124]
The readme has a link to https://www.netwerkdigitaalerfgoed.nl/en/knowledge-services/usable-digital-heritage/network-of-terms/, but that page no longer exists. Can you fix the link to the correct page or perhaps replace it with a link to the (English) FAQ?

**Comment by sdevalk** [comment]
Thanks for reporting!

Fixed in https://github.com/netwerk-digitaal-erfgoed/network-of-terms-api/commit/a3db3cab10f7f3b0eb019e90165dd55581fb61c6. We could revert this fix at some point, if the English version of the NDE site is available again.
