### ISSUE TITLE
Bug: empty result set if source contains one term

### ISSUE THREAD

**Issue by sdevalk** [netwerk-digitaal-erfgoed/network-of-terms-api#13]
If a source returns just one term, this term is ignored by the `TermsTransformer`, yielding an empty result set. For example:

`./bin/run sources:query --identifiers cht --query rembrandt --loglevel info`

The `TermsTransformer` wrongly assumes that the source contains more terms:

https://github.com/netwerk-digitaal-erfgoed/network-of-terms-comunica/blob/master/src/services/terms.ts#L37

We need to refactor this code a bit. Point of attention: terms arrive in a stream, so we don't know beforehand how many terms there are.

**Comment by ddeboer** [comment]
This was resolved in #30: 

```bash
bin/run sources:query --uris https://data.cultureelerfgoed.nl/PoolParty/sparql/term/id/cht --query "rembrandt"
Source Name                  Term URI                                                                          Preferred Labels Alternative Labels
Cultuurhistorische Thesaurus https://data.cultureelerfgoed.nl/term/id/cht/89ce37a3-8bd2-4172-9bff-f95243f72c11 Rembrandtbijbels Rembrandtbijbel
```
