### ISSUE TITLE
Duplicate terms returned

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/network-of-terms-api#225]
For example https://termennetwerk.netwerkdigitaalerfgoed.nl/?q=das&datasets=https://data.cultureelerfgoed.nl/PoolParty/sparql/term/id/cht returns ‘dassenjachten’ twice.

**Comment by sdevalk** [comment]
Some rough tests, for further analysis:

The (minimalized) query underneath searches for `dassen` in the CHT and returns (among others) two terms with the same URI, `https://data.cultureelerfgoed.nl/term/id/cht/5a45f71b-ab7d-443e-b498-5e4570ca696b` (label = `dassenjachten`).

Endpoint: https://data.cultureelerfgoed.nl/PoolParty/sparql/term/id/cht

```sparql
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
    ?uri a skos:Concept ;
        skos:prefLabel ?prefLabel .
}
WHERE {
    ?uri ?predicate ?label .
    VALUES ?predicate { skos:prefLabel skos:altLabel }
    FILTER(LANG(?label) = "nl")
    FILTER(CONTAINS(LCASE(?label), LCASE("dassen")))
    ?uri skos:prefLabel ?prefLabel .
    FILTER(LANG(?prefLabel) = "nl")
}
LIMIT 1000
```

However, if I search for `dassenj` then the query returns just one term:

```sparql
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
    ?uri a skos:Concept ;
        skos:prefLabel ?prefLabel .
}
WHERE {
    ?uri ?predicate ?label .
    VALUES ?predicate { skos:prefLabel skos:altLabel }
    FILTER(LANG(?label) = "nl")
    FILTER(CONTAINS(LCASE(?label), LCASE("dassenj")))
    ?uri skos:prefLabel ?prefLabel .
    FILTER(LANG(?prefLabel) = "nl")
}
LIMIT 1000
```

The same issue exists in another source, the ABR (also managed in PoolParty).

If I search for `zwaard`, the query returns (among others) two terms with the same URI, `https://data.cultureelerfgoed.nl/term/id/abr/01628d5b-e55a-48f1-9992-8f107671d728z` (label = `anderhalfhandzwaard`).

Endpoint: https://data.cultureelerfgoed.nl/PoolParty/sparql/term/id/abr

```sparql
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
    ?uri a skos:Concept ;
        skos:prefLabel ?prefLabel .
}
WHERE {
    ?uri ?predicate ?label .
    VALUES ?predicate { skos:prefLabel skos:altLabel }
    FILTER(LANG(?label) = "nl")
    FILTER(CONTAINS(LCASE(?label), LCASE("zwaard")))
    ?uri skos:prefLabel ?prefLabel .
    FILTER(LANG(?prefLabel) = "nl")
}
LIMIT 1000
```

However, if I search for `dzwaard` then the query returns just one term:

```sparql
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
    ?uri a skos:Concept ;
        skos:prefLabel ?prefLabel .
}
WHERE {
    ?uri ?predicate ?label .
    VALUES ?predicate { skos:prefLabel skos:altLabel }
    FILTER(LANG(?label) = "nl")
    FILTER(CONTAINS(LCASE(?label), LCASE("dzwaard")))
    ?uri skos:prefLabel ?prefLabel .
    FILTER(LANG(?prefLabel) = "nl")
}
LIMIT 1000
```
