### ISSUE TITLE
Add highlevel documentation of the network-of-terms

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/network-of-terms-api#374]
Regarding the network-of-terms-api repository as the central repository for the network-of-terms I would expect to find a high level overview of the Network-of-Terms functionality, maybe similar to what is being published in FAQ in the front-end. This would be very helpful for people from outside our network that are interested in our work.

**Comment by ddeboer** [comment]
Would it help to add a translation of (the English version is somewhat outdated) the FAQ section:

> Het Termennetwerk is een zoekmachine voor termen. Je voert er een zoekvraag in – zoals ‘Rembrandt’ – en het Termennetwerk zoekt vervolgens rechtstreeks, realtime in terminologiebronnen naar overeenkomende termen. Uit de termen die dit oplevert kun je een keuze maken. Bijvoorbeeld ‘Rembrandt’ in RKDartists of ‘Rembrandt Harmensz. van Rijn’ in de Nederlandse Thesaurus van Auteursnamen.

to https://github.com/netwerk-digitaal-erfgoed/network-of-terms-api#network-of-terms?

**Comment by EnnoMeijers** [comment]
That would be a good start, I think we should also add the fact that an URI is returned for terms.
