### ISSUE TITLE
Sort narrower, broader and related terms

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/network-of-terms-api#380]
https://github.com/netwerk-digitaal-erfgoed/network-of-terms-demo/issues/364

@sdevalk Do you agree?

**Comment by sdevalk** [comment]
Absolutely! We already [sort the altLabels](https://github.com/netwerk-digitaal-erfgoed/network-of-terms-api/pull/146) - sorting the labels of the narrower, broader and related terms is a great addition!
