### ISSUE TITLE
Searching on terms with diacritical marks

### ISSUE THREAD

**Issue by raboof** [netwerk-digitaal-erfgoed/network-of-terms-api#426]
When I perform the query:

```
{"query":"query Terms ($sources: [ID]!, $query: String!) {\n                terms (sources: $sources query: $query) {\n                  source {\n                    name\n                    uri\n                    alternateName\n                    creators {\n                      name\n                      alternateName\n                    }\n                  }\n                  result {\n                    ... on Terms {\n                      terms {\n                        uri\n                        prefLabel\n                        altLabel\n                        hiddenLabel\n                        scopeNote\n                        seeAlso\n                        broader {\n                          uri\n                          prefLabel\n                        }\n                        narrower {\n                          uri\n                          prefLabel\n                        }\n                        related {\n                          uri\n                          prefLabel\n                        }\n                      }\n                    }\n                    ... on Error {\n                      __typename\n                      message\n                    }\n                  }\n                }\n              }","variables":{"sources":["https://data.netwerkdigitaalerfgoed.nl/rkd/rkdartists/sparql"],"query":"Joan Miró"}}
```

I get the error:

```
Invalid SPARQL endpoint response from https://api.data.netwerkdigitaalerfgoed.nl/datasets/rkd/rkdartists/services/rkdartists/sparql (HTTP status 500):Virtuoso 37000 Error XM029: Free-text expression, line 0: Invalid character in free-text search expression, it may not appear outside quoted string at �SPARQL query:define sql:big-data-const 0 define output:format "HTTP+TTL text/turtle" CONSTRUCT {  ?uri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#Concept>.  ?uri <http://www.w3.org/2004/02/skos/core#prefLabel> ?schema_name.  ?uri <http://www.w3.org/2004/02/skos/core#altLabel> ?schema_alternateName.  ?uri <http://www.w3.org/2004/02/skos/core#scopeNote> ?schema_description.}WHERE {  {    ?uri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type.    VALUES ?type {      <http://schema.org/Person>      <http://schema.org/Organization>    }    ?uri ?name ?label.    VALUES ?name {      <http://schema.org/name>      <http://schema.org/alternateName>    }    OPTIONAL { ?uri <http://schema.org/name> ?schema_name. }    OPTIONAL { ?uri <http://schema.org/alternateName> ?schema_alternateName. }    OPTIONAL { ?uri <http://schema.org/description> ?schema_description. }    FILTER(<bif:contains>(?label, REPLACE(REPLACE("Joan Miró", "[.,]", " "), "(?<!AND)(?<!OR)[[:space:]]+(?!AND)(?!OR)(?!$)(?![[:space:]])", " AND ", "i")))  }}LIMIT 1000
```

It looks like terms with diacritical marks must be quoted when passed to `bif:contains`: manually testing with `url -H "Content-Type: application/sparql-query" -d '@/tmp/query.txt' https://api.data.netwerkdigitaalerfgoed.nl/datasets/rkd/rkdartists/services/rkdartists/sparql` and the following query:

```
CONSTRUCT
  {    ?uri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#Concept>.
    ?uri <http://www.w3.org/2004/02/skos/core#prefLabel> ?schema_name.
    ?uri <http://www.w3.org/2004/02/skos/core#altLabel> ?schema_alternateName.
    ?uri <http://www.w3.org/2004/02/skos/core#scopeNote> ?schema_description.
  }
WHERE
  {
    {
      ?uri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type.
      VALUES ?type {      <http://schema.org/Person>      <http://schema.org/Organization>    }
      ?uri ?name ?label.
      VALUES ?name {      <http://schema.org/name>      <http://schema.org/alternateName>    }
      OPTIONAL { ?uri <http://schema.org/name> ?schema_name. }
      OPTIONAL { ?uri <http://schema.org/alternateName> ?schema_alternateName. }
      OPTIONAL { ?uri <http://schema.org/description> ?schema_description. }
      FILTER(<bif:contains>(?label, "Joan AND 'Miró'"))
    }
  }
LIMIT 1000
```

does work, while without the quotes it produces the error similar to the one above.

**Comment by ddeboer** [comment]
Heb @raboof, thanks for taking the time to investigate and report this issue! 

As it happens, we’re right in the process of solving this issue (in https://github.com/netwerk-digitaal-erfgoed/network-of-terms-api/pull/398). I expect that we can merge and release that shortly and then enable the new functionality in the demonstrator too (https://github.com/netwerk-digitaal-erfgoed/network-of-terms-demo/issues/411).

**Comment by raboof** [comment]
> Heb @raboof, thanks for taking the time to investigate and report this issue!
> 
> As it happens, we’re right in the process of solving this issue (in #398). I expect that we can merge and release that shortly and then enable the new functionality in the demonstrator too ([netwerk-digitaal-erfgoed/network-of-terms-demo#411](https://github.com/netwerk-digitaal-erfgoed/network-of-terms-demo/issues/411)).

Ha, great, I hadn't recognized is as such yet but indeed that looks like it'd fix searching for "Joan Miró".

As a slightly-different-but-related issue, it would be great if searching for "Joan Miro" would also match this record, but I suspect that'd require changes on the Virtuoso side first, so I guess it doesn't make sense to track that here yet ;)

**Comment by ddeboer** [comment]
[Searching for `miró`](https://termennetwerk.netwerkdigitaalerfgoed.nl/?q=miró&datasets=https://data.netwerkdigitaalerfgoed.nl/rkd/rkdartists/sparql) now works in the demonstrator, too.

@raboof You’re right, whether `miro` also matches `miró` in the original term source depends on the configuration of the Virtuoso endpoint in question (in particular, the [`XAnyNormalization` flag](http://docs.openlinksw.com/virtuoso/dbadm/#ini_i18n)), which is out of control of the Network of Terms.

**Comment by raboof** [comment]
(just to close the circle here: the Virtuoso config has been edited, so https://termennetwerk.netwerkdigitaalerfgoed.nl/?q=miro&datasets=https://data.netwerkdigitaalerfgoed.nl/rkd/rkdartists/sparql now also finds Miró :tada: )
