### ISSUE TITLE
Abort request to slow or unreachable terminology source

### ISSUE THREAD

**Issue by sdevalk** [netwerk-digitaal-erfgoed/network-of-terms-api#45]
A terminology source can be slow or unreachable. If it takes too much time to query the source, we should abort the request and inform the user about this. The default timeout of Comunica is 60 seconds, but this is too long for our use case. We should change this to e.g. 5 or 10 seconds.

**Comment by ddeboer** [comment]
Comunica currently doesn’t handle timeouts, so we either have to wait for/contribute https://github.com/comunica/comunica/issues/745 or be creative with [`Promise.race`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race) on our side.
